### ISSUE TITLE
schedule master jobs a bit less

### ISSUE THREAD

**Issue by samoht** [avsm/mirage-ci#1]
Today on every PR merge, https://ci.ocaml.io/branch is taking all the resources for a few minutes. That would be great to avoid this. I can see 2 ways to do this (there are probably others):

- build the master branch only "once per X", where X can be hours, days.
- give a lowest priority to master builds, so that PR builds are always scheduled first

**Comment by kit-ty-kate** [comment]
Fixed by #20
