### ISSUE TITLE
Revdeps are not testing the right version

### ISSUE THREAD

**Issue by samoht** [avsm/mirage-ci#3]
For the `js_of_ocaml.3.0` release, some rev deps tests are testing `js_of_ocaml.2.8.1`:

https://ci.ocaml.io/log/saved/docker-run-2192acb8ef87e878d8b4151a6f1d15ba/69bf79f8f8f805f5e8364475bcf75b29e76f067e

The revdeps should force the version of the package to the one being tested -- this will help keeping the revdeps list in a size of reasonable proportions.

**Comment by kit-ty-kate** [comment]
Fixed by #14 and #21
