### ISSUE TITLE
OpenSUSE 42.2 images are flaky/broken

### ISSUE THREAD

**Issue by samoht** [avsm/mirage-ci#4]
```
The which command shows the full pathname of a specified program, if
the specified program is in your PATH.
package zlib-devel is not installed
# The following new OS packages need to be installed: gmp-devel m4 ncurses-devel perl-Pod-Html zlib-devel
The following command needs to be run through "sudo":
    yum -y update
Redirecting to '/usr/bin/dnf -y update' (see 'man yum2dnf')

Error: Failed to synchronize cache for repo 'updates'
OS package update failed
```

**Comment by avsm** [comment]
not clear why opensuse is using yum instead of zypper here, hm

**Comment by dbuenzli** [comment]
Is https://github.com/ocaml/opam-depext/pull/67 by @jpdeplaix maybe solving the problem ?

**Comment by kit-ty-kate** [comment]
I doubt it. It seems that it doesn't even detect the right OS as @avsm pointed out :/ Something must be wrong either in the detection method or in the way the images are created or installed, I suppose.

**Comment by kit-ty-kate** [comment]
I think this issue can be closed now as OpenSUSE images seem to work well.
