### ISSUE TITLE
cancel previous runs on new commits

### ISSUE THREAD

**Issue by samoht** [avsm/mirage-ci#5]
It would be useful to save resource usage and fastest feedback loop if the old runs of a pull-request were canceled whenever a new commit is added to a PR. CircleCI has such a feature and it has been pretty useful on the projects I used it.

**Comment by kit-ty-kate** [comment]
Related to https://github.com/moby/datakit/issues/625

**Comment by avsm** [comment]
I'm closing this as its unlikely the upstream project will do this. @talex5 is working on a refresh of the CI engine that can have this feature engineered in...
