### ISSUE TITLE
filter out deleted packages on PRs for revdeps

### ISSUE THREAD

**Issue by samoht** [avsm/mirage-ci#7]
It doesn't make sense to revdep test deleted packages (or packages who appeared once on the PR but then get removed with a force-push), this give this kind of error:

https://github.com/ocaml/opam-repository/pull/9718#issuecomment-312760127
```
=== docker run --rm
sha256:0a173b17294142c850e13199c4f6daedc8fbe1b8e3b5b8ce805b60f1fc5c8687 opam
list -s --color=never --depends-on oth.2.9
--installable
[ERROR] Package oth has no version 2.9.
```

**Comment by kit-ty-kate** [comment]
Fixed by #19
